name: nbbda

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - networkx
  - scikit-learn
  - jupyterlab
  - ipykernel
  - pip
  - python-igraph
